name: Deploy GitHub Pages

on:
  push:
    branches:
      - main  # Ветка, которую вы используете для публикации

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm install
        working-directory: ./Roselab/Roselab  # Укажите путь к вашему проекту
      - name: Build
        run: npm run build
        working-directory: ./Roselab/Roselab  # Укажите путь к вашему проекту
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./Roselab/Roselab/build  # Укажите путь к папке с собранным сайтом
          enablement: true
